spring:
  application:
    name: cash

  datasource:
    url: jdbc:postgresql://localhost:5433/cashdb
    username: cash
    password: cash
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
