spring:
  application:
    name: cash

  datasource:
    url: jdbc:postgresql://localhost:5433/${POSTGRES_DB:cashdb}
    username: ${POSTGRES_USER:cash}
    password: ${POSTGRES_PASSWORD:cash}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
